# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-04 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.CharField(default='admin', max_length=40),
        ),
    ]
